version: '3'

networks:

  default:

services: 
  cluster:
    build:
      context: .
      dockerfile: ./Dockerfile_Tensorflow
    volumes:
      - ./:/service
    networks:
      - default
    tty: true
