version: '3'

networks:

  default:

services: 
  cluster:
    build:
      context: .
      dockerfile: ./NNTPA/Dockerfile_Tensorflow
    volumes:
      - ./NNTPA:/service/NNTPA
    networks:
      - default
    tty: true
